### ISSUE TITLE
Problem of load from MemConst

### ISSUE THREAD

**Issue by hnemati** [kth-step/HolBA#109] opened 2020-02-21 11:01 UTC
It seems to me that HolBA has problem with all Load operations from memory of type BExp_MemConst. Here are two examples I tried:

Simple case:  
```sml
val e1 = ``BExp_Load (BExp_MemConst Bit64 Bit8 MM) (BExp_Const (Imm64 (0x8w :word64))) BEnd_LittleEndian Bit64``;
EVAL ``bir_eval_exp ^e1 (BEnv (K NONE))``;
```

A bit more complex case:
```sml
val e2 =
``(BExp_UnaryExp BIExp_Not
         (BExp_BinPred BIExp_Equal
            (BExp_Load
               (BExp_Store (BExp_MemConst Bit64 Bit8 MM)
                  (BExp_BinExp BIExp_Plus
                     (BExp_Const (Imm64 (0x800003FFFFFFFFCBw :word64)))
                     (BExp_Const (Imm64 (45w :word64)))) BEnd_LittleEndian
                  (BExp_Const (Imm64 (0x8000000000000000w :word64))))
               (BExp_BinExp BIExp_Plus
                  (BExp_Const (Imm64 (0x800003FFFFFFFFCBw :word64)))
                  (BExp_Const (Imm64 (45w :word64)))) BEnd_LittleEndian Bit64)
            (BExp_Const (Imm64 (0w :word64)))))
``
EVAL ``bir_eval_exp ^e2 (BEnv (K NONE))``; 
```

**Comment by didriklundberg** [comment] 2020-02-24 15:01
There is now a simpset for this in the [load_store_dev branch](https://github.com/kth-step/HolBA/tree/load_store_dev). @hnemati, you will have to extend this to cover all cases you need (like recursive stores). @andreaslindner should maybe pull this to master, you decide.

**Comment by didriklundberg** [comment] 2020-02-24 15:05
Here's a usage suggestion using the expression above:

```sml
val e2 = ``(BExp_UnaryExp BIExp_Not
         (BExp_BinPred BIExp_Equal
            (BExp_Load
               (BExp_Store (BExp_MemConst Bit64 Bit8 MM)
                  (BExp_BinExp BIExp_Plus
                     (BExp_Const (Imm64 (0x800003FFFFFFFFCBw :word64)))
                     (BExp_Const (Imm64 (45w :word64)))) BEnd_LittleEndian
                  (BExp_Const (Imm64 (0x8000000000000000w :word64))))
               (BExp_BinExp BIExp_Plus
                  (BExp_Const (Imm64 (0x800003FFFFFFFFCBw :word64)))
                  (BExp_Const (Imm64 (45w :word64)))) BEnd_LittleEndian Bit64)
            (BExp_Const (Imm64 (0w :word64)))))
``;

val restr_eval_tm = computeLib.RESTR_EVAL_CONV [``bir_eval_load``, ``bir_eval_store``] ``bir_eval_exp ^e2 (BEnv (K NONE))``;

SIMP_RULE (std_ss++bir_load_store_ss) [] restr_eval_tm;
```

**Comment by didriklundberg** [comment] 2020-02-24 15:17
Anyhow, the reason why the above evaluation doesn't terminate is because it boils down to the recursive `n2l` definition being applied to an expression with a free variable, so rewriting loops. You can see it if you use `RESTR_EVAL_CONV` with `n2l`. I wouldn't really call this a bug.

**Comment by andreaslindner** [comment] 2020-02-24 15:25
I don't know, before adding this to master we should probably change the name to reflect that this is for symbolic evaluation of expressions. As mentioned on the slack already, this only covers a very specific case and is like this not applicable to arbitrary expressions.

If we need it, this should probably be engineered more and then we can have it in master.

**Comment by andreaslindner** [comment] 2020-02-24 15:26
Just to make it clear, this is not a bug, this is a new feature where Didrik suggested a way of adding this. In HOL4 in general, EVAL doesn't work on arbitrary definitions.

**Comment by didriklundberg** [comment] 2020-10-22 13:31
Since the solution to this - or at least the remedy to the immediate problem - has recently been merged into master, I will close this issue.

**Closed by didriklundberg** 2020-10-22 13:31 UTC
Labels: enhancement
